//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Wireframe

protocol ___VARIABLE_moduleName___WireframeProtocol: WireframeProtocol {
}

// MARK: - View

protocol ___VARIABLE_moduleName___ViewProtocol: ViewProtocol {
}

// MARK: - Presenter

protocol ___VARIABLE_moduleName___PresenterProtocol: PresenterProtocol {
}

// MARK: - Formatter

protocol ___VARIABLE_moduleName___FormatterProtocol: FormatterProtocol {
}

// MARK: - Interactor

protocol ___VARIABLE_moduleName___InteractorProtocol: InteractorProtocol {
}
